[package]
name = "money"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pyu_rust_util = "0.1.66"
rand = "0.8.5"
